import assert from 'node:assert/strict';
import * as THREE from 'three';
import {applyRendererPacket} from '../three_vrm_packet_adapter';
const weights=new Map<string,number>();const lookAt={autoUpdate:true,yaw:12,pitch:7};const head=new THREE.Object3D();const vrm:any={lookAt,humanoid:{getNormalizedBoneNode:()=>head},expressionManager:{getExpression:(n:string)=>['aa','happy','blinkLeft'].includes(n)?{}:null,setValue:(n:string,w:number)=>weights.set(n,w),update(){}},update(){}};
const ctx:any={vrm,animationActions:new Map()};const packet=(commands:any[]=[],reset:string[]=[])=>({schema_version:1,sequence:0,source_event:'test',model:{name:'test',sha256:'test'},commands,reset});const expr=(target:string,logical:string,channel:string)=>({op:'set_expression',target,channel,duration_ms:0,start_offset_ms:0,source:'test',values:{weight:1,logical_expression:logical}});
applyRendererPacket(ctx,packet([expr('A','aa','mouth'),expr('Joy','happy','expression:face'),expr('Blink_L','blinkLeft','expression:blink')]));
assert.equal(weights.get('aa'),1);assert.equal(weights.get('happy'),1);assert.equal(weights.get('blinkLeft'),1);
applyRendererPacket(ctx,packet([],['expressions:mouth']));assert.equal(weights.get('aa'),0);assert.equal(weights.get('happy'),1);assert.equal(weights.get('blinkLeft'),1);
applyRendererPacket(ctx,packet([],['expressions:blink']));assert.equal(weights.get('happy'),1);assert.equal(weights.get('blinkLeft'),0);
applyRendererPacket(ctx,packet([{op:'look_at_angles',target:'camera',channel:'look_at',duration_ms:0,start_offset_ms:0,source:'test',values:{yaw_deg:20,pitch_deg:-10}}]));assert.equal(lookAt.yaw,20);assert.equal(lookAt.pitch,-10);assert.equal(lookAt.autoUpdate,false);
applyRendererPacket(ctx,packet([],['look_at']));assert.equal(lookAt.yaw,0);assert.equal(lookAt.pitch,0);
console.log('4 renderer adapter regressions passed: VRM0 aliases, mouth isolation, blink isolation, gaze state/reset');
