"""Generate the product API index from the frozen root contract and source."""
from __future__ import annotations

import inspect
import json
import re
from pathlib import Path

import ai_character_engine as engine


ROOT = Path(__file__).resolve().parents[1]


def render_reference():
    manifest = json.loads((ROOT / "docs/public_api_v1_stable.json").read_text(encoding="utf-8"))
    symbols = manifest["symbols"]
    assert {s["name"] for s in symbols} == set(engine.__all__)
    lines = [
        "# Stable root API reference", "",
        f"{len(symbols)} exports in `ai_character_engine`, version {engine.__version__}.", "",
        "Import these names from the package root. This index records the frozen",
        "root call shapes and links to implementations for full annotations, defaults",
        "and methods. Optional parameters are marked `= …`; this is contract notation,",
        "not executable Python. Implementation-module imports are outside the root freeze.", "",
        "[Compatibility policy](compatibility.md) · [Architecture](architecture.md) ·",
        "[Machine-readable contract](public_api_v1_stable.json)", "",
        "Generated by `python tools/generate_api_reference.py`.", "",
    ]
    for symbol in symbols:
        name = symbol["name"]
        obj = getattr(engine, name)
        parameters = []
        keyword_marker = False
        for parameter in symbol.get("parameters", []):
            kind = parameter["kind"]
            if kind == "keyword_only" and not keyword_marker:
                parameters.append("*")
                keyword_marker = True
            prefix = "*" if kind == "var_positional" else "**" if kind == "var_keyword" else ""
            if prefix:
                keyword_marker = True
            suffix = "" if parameter["required"] or prefix else " = …"
            parameters.append(prefix + parameter["name"] + suffix)
        shape = name + ("(" + ", ".join(parameters) + ")" if symbol["kind"] in {"class", "function"} else "")
        lines += [f"## {name}", "", f"`{shape}`", "", f"Kind: {symbol['kind']}. Stability: {symbol['stability']}.", ""]
        try:
            source = Path(inspect.getfile(obj)).resolve().relative_to(ROOT)
        except (TypeError, ValueError):
            source = Path("src/ai_character_engine/__init__.py")
        module = getattr(obj, "__module__", "")
        if module.startswith("ai_character_engine"):
            doc = inspect.getdoc(obj)
            if doc and not doc.startswith(name + "("):
                description = doc.split("\n\n", 1)[0].replace("\n", " ")
                description = re.sub(r"\s+in v0\.\d+(?:\.\d+)?", "", description)
                description = re.sub(r"v0\.\d+(?:\.\d+)?\s*", "", description)
                lines += [description, ""]
        lines += [f"[Source](../{source.as_posix()})", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    (ROOT / "docs/api-reference.md").write_text(render_reference(), encoding="utf-8")
